Job handling library.
JaydenElliott/remote-linux-worker pull request #2
Opened 2022-04-19 10:32 UTC by JaydenElliott

## Summary
This PR introduces the first half of the remote-linux-woker library implementation:
- Ability to start processes
- Stop processes
- Capture process output
- Capture process status
- Stream the process output

The next PR will introduce the public facing gRPC server interface that will utilize the above functionality, as well as an example client CLI.

## Relevant Notes

### Streaming Approach Change 
The implemented streaming logic is code correct, however, not very elegant. My original approach, although much cleaner, introduced a race condition that I believe was not solvable.

I have included a comment on this PR explaining the above scenario and the logic in my new solution.

### Tokio and STD library channels
The code includes mpsc channels from both tokio and the standard library; this is intentional. The tokio channel is only used in `stream_job()` due to the requirements of gRPC streaming in `tonic`.

2022-04-19 10:33 UTC, JaydenElliott commented
### Streaming Approach

The implemented streaming logic is code correct, however, not very elegant. My original approach, although much cleaner, introduced a race condition that I believe was not solvable.

#### Original Approach
 Introduce a channel into the `Job` object (`job.tx` and `job.rx`) and use this in the following way:
1. When the client begins streaming, a new thread would be initialized (thread 2) and set an atomic bool `streaming` to be true. 
2. This 2nd thread would then send the job history `job.output` to the client.
3. The first thread (the one processing the jobs and populating `job.output`) would check the `streaming` bool every time it receives new output. If `streaming` is set to true, it would send the new output down the channel (using `job.tx`).
4. The receiver `job.rx` would be sent in the grpc response establish the streaming connection.


#### Race Condition Scenario
1. Thread 1 (processing thread) receives a new output value. It firstly checks the `streaming` bool and it is false.
2. The client initiates a request and thread 2 sets `streaming` to true.
3. Thread 2 sends the job history `job.output` to the client.
4. Thread 1 adds the new output value to the `job.output` vector.
5. Thread 1 receives another output, finds `streaming` to be true and streams the results from then on.

In this scenario, thread 2 failed to send one of the output values to the client. A race condition occurs in all scenarios in which we first send the client the `job.output` and then stream the results via a channel.

#### New approach
1. When the client sends a streaming request a second thread is initialized. This thread sends the job history `job.output` to the client.
2. While the job is still running, the thread will continuously check for new additions to the output vector. In the event that there is new output, this new output is sent to the client.
3. When the job has finished, the thread sends the remaining elements of the output and then closes the stream.

Because this method is only dependent on `job.output` there exists no scenario where the algorithm will fail to send some output.

2022-04-19 18:56 UTC, timothyb89 requested changes
Side note, a quick `cargo clippy` run would catch a few nitpicks.

2022-04-19 18:56 UTC, timothyb89 commented on src/lib/lib.rs
> +mod processing;
Just a heads up, nothing here is `pub` so the library isn't really usable as a library.

2022-04-19 18:56 UTC, timothyb89 commented on src/lib/jobs.rs
> +        });
It's pretty odd to resort to OS threads when already running in an async runtime. I'd say this should be `spawn_blocking()` at a minimum but I'm not sure `execute_command()` needs to be blocking to begin with.

2022-04-19 18:56 UTC, timothyb89 commented on src/lib/jobs.rs
> +            .join()
A blocking `.join()` call is very problematic in an async function.

An unrelated nitpick: this `status` shadows another unrelated `status`. I know it's basically fine to do this in Rust but I did find it surprising.

2022-04-19 18:56 UTC, timothyb89 commented on src/lib/jobs.rs
> +        mem::drop(lock_handle);
I could see relying on `mem::drop(...)` leading to some odd footguns when there's function exit points between the lock and unlock. It's probably nicer in general to let scoping rules handle this by chaining calls (or using nested scopes where that isn't possible):

```suggestion
        let pid = self.pid
            .lock()
            .await
            .ok_or(RLWServerError(
                "There is no running process associated with this job".to_string(),
            ))?
            .to_string();
```

2022-04-19 18:56 UTC, timothyb89 commented on src/lib/jobs.rs
> +            ) {
This is pretty unusual. What about using `while let ...`?

```suggestion
            while let status_response::ProcessStatus::Running(true) = *self.status.lock().await {
```

2022-04-19 18:56 UTC, timothyb89 commented on src/lib/jobs.rs
> +                        output: vec![output[read_idx]],
It's a bit odd (and probably pretty inefficient) that we just send single bytes here, let alone wrapping each one inside a vec.

2022-04-19 18:56 UTC, timothyb89 commented on src/lib/jobs.rs
> +            );
The `nix` or `libc` crates will let you kill child processes without having to shell out.

2022-04-19 20:11 UTC, espadolini commented on src/lib/jobs.rs
> +            while matches!(
This is a busyloop that keeps checking for the length, it should be made to wait on some event instead.

2022-04-19 20:11 UTC, espadolini commented on src/lib/jobs.rs
> +        let pid = lock_handle
You have no guarantee that this `pid` is still the pid of the process that you meant to kill; you risk signaling some other process, if your process dies and gets reaped between this and the point where you signal it.

2022-04-20 09:03 UTC, JaydenElliott commented on src/lib/lib.rs
> +mod processing;
I was originally planning on having the only exposed function be `start_server()` (see design doc), which would then expose the start, stop, query, status functions through gRPC requests.

I potentially misinterpreted the instructions, would you prefer these functions be public and then a separate binary would be written for the server? If so, i'm happy to do that, no code needs changing.

2022-04-20 10:58 UTC, JaydenElliott commented on src/lib/jobs.rs
> +            ) {
I was unaware that the if let ... syntax extended to while lets also, I like it thanks.

2022-04-20 10:58 UTC, JaydenElliott commented on src/lib/jobs.rs
> +            ) {
Resolved.

2022-04-20 11:00 UTC, JaydenElliott commented on src/lib/jobs.rs
> +                        output: vec![output[read_idx]],
Updated the processor logic to send each "line" returned from the process rather than each byte. Updated the streaming logic to do this also.

2022-04-20 11:06 UTC, JaydenElliott commented on src/lib/jobs.rs
> +        mem::drop(lock_handle);
From a developer point of view I prefer seeing an explicit drop over the nested scope syntax but I can definitely see your point on it causing some strange behavior.

Have removed all mem::drop(). Thanks for that.

2022-04-20 12:50 UTC, JaydenElliott commented on src/lib/jobs.rs
> +            .join()
Resolved. 
Nitpicks are most welcome, keep them coming.

2022-04-20 13:05 UTC, JaydenElliott commented on src/lib/jobs.rs
> +            );
Resolved and removed a lot of unnecessary code, thanks.

2022-04-20 13:06 UTC, JaydenElliott commented on src/lib/jobs.rs
> +        let pid = lock_handle
Updated stop command. It now checks if the job is still running before sending the signal.

2022-04-20 13:11 UTC, JaydenElliott commented on src/lib/jobs.rs
> +            while matches!(
I have spent the night trying to resolve this. I attempted a few event signaling methods (using an empty channel to notify of new output, using a condvar etc.), however I ran into a lot of issues (primarily with the rx and tx not syncing correctly across async threads/functions).  

Leaving it for now, but will continue on this tomorrow evening.

2022-04-20 17:50 UTC, espadolini commented on src/lib/jobs.rs
> +        let pid = lock_handle
The same race condition still exists, the `kill` and the `waitpid` are completely unsynchronized.

2022-04-20 17:52 UTC, espadolini commented on src/lib/processing.rs
> +    for line in stdout_reader.lines() {
This will blow up if the process sends non-utf8 data to stdout or stderr, and it'll never output anything if the process is not outputting newlines - what if it's not writing text but some binary data to stdout?

2022-04-20 22:17 UTC, JaydenElliott commented on src/lib/jobs.rs
> +        let pid = lock_handle
Would using a synchronous lock solve this?

2022-04-20 22:24 UTC, JaydenElliott commented on src/lib/processing.rs
> +    for line in stdout_reader.lines() {
Good point, I should have thought about that, reverted back to sending bytes.

2022-04-20 23:01 UTC, timothyb89 commented on src/lib/processing.rs
> +        }
There may still be a compromise between reading lines and reading individual bytes: reading blocks of data as they arrive. The boring old [`Read::read()`](https://doc.rust-lang.org/stable/std/io/trait.Read.html#tymethod.read) might be a good place to start.

2022-04-21 00:15 UTC, JaydenElliott commented on src/lib/jobs.rs
> +            while matches!(
@espadolini Resolved. Added a signal that is triggered when new output is received. This signal will wake up the streaming thread, which will then send the output to the client.

Thanks for this heads up, a busy loop was definitely the wrong approach.

2022-04-21 08:56 UTC, JaydenElliott commented on src/lib/processing.rs
> +        }
Updated the code to send the data in chunks, good idea thanks.

2022-04-21 09:04 UTC, espadolini commented on src/lib/jobs.rs
> +        let pid = lock_handle
The issue is the synchronization between the `waitpid` syscall done by the blocking call to `std::process::Child::wait()` and the signaling: in the instant that `waitpid` returns, some other process can be spawned with the exact same pid.

You can switch to `tokio::process::Child`, whose `wait()` method is asynchronous and cancel-safe, meaning that _while not actively polling it_ you can get the process' pid and signal it.

2022-04-22 01:24 UTC, JaydenElliott commented on src/lib/jobs.rs
> +        let pid = lock_handle
Is there any other method which could solve this? I spent quite a bit of time swapping to the tokio `Child` and was having a lot of problems with `execute_command()` now being async and causing other deadlocks throughout the code.

Given I only have tonight and the weekend left to finish the project I think I should focus on the server + client implementation and come back to fix this issue if I get time.

2022-04-22 01:33 UTC, JaydenElliott commented on src/lib/jobs.rs
> +        let pid = lock_handle
I added my `tokio::Child` implementation attempt in the latest commit to a new branch https://github.com/JaydenElliott/remote-linux-worker/tree/process-handling-async if you want to have a look.

2022-04-22 06:26 UTC, espadolini approved these changes
I think everything but the `waitpid` race condition has been addressed.

2022-04-22 16:11 UTC, timothyb89 approved these changes
Just a couple of small nitpicks on my end!

2022-04-22 16:11 UTC, timothyb89 commented on src/lib/processing.rs
> +        buf = [0u8; OUTPUT_CHUNK_SIZE_BYTES];
The buffer doesn't really need to be cleared each time, the first `n` bytes will always be overwritten by the most recent read.

2022-04-22 16:11 UTC, timothyb89 commented on src/lib/processing.rs
> +    while let Ok(size) = stdout_reader.read(&mut buf) {
It may be fine if intentional, but `while let Ok(...) = ...` means we'll ignore read errors.

2022-04-22 21:58 UTC, JaydenElliott commented on src/lib/processing.rs
> +        buf = [0u8; OUTPUT_CHUNK_SIZE_BYTES];
Good point, I ignore n+1 ... bytes on the send anyway. Resolved.

2022-04-22 21:58 UTC, JaydenElliott commented on src/lib/processing.rs
> +    while let Ok(size) = stdout_reader.read(&mut buf) {
Updated to a loop {match {}}. Thanks

2022-04-22 22:02 UTC, merged